name: String Parser with 20 Inputs

on:
  workflow_dispatch:
    inputs:
      input_string:
        description: 'Enter 20 comma-separated values'
        required: true
        default: 'val1,val2,val3,val4,val5,val6,val7,val8,val9,val10,val11,val12,val13,val14,val15,val16,val17,val18,val19,val20'

jobs:
  parse_and_use_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Show the original input string
        run: echo "Input String: ${{ github.event.inputs.input_string }}"

      - name: Parse the string and export as environment variables
        id: parse
        run: |
          IFS=',' read -ra VALUES <<< "${{ github.event.inputs.input_string }}"
          for i in "${!VALUES[@]}"; do
            index=$((i + 1))
            echo "value$index=${VALUES[i]}" >> $GITHUB_ENV
          done

      - name: Use parsed values
        run: |
          echo "Value 1: $value1"
          echo "Value 2: $value2"
          echo "Value 3: $value3"
          echo "Value 4: $value4"
          echo "Value 5: $value5"
          echo "Value 6: $value6"
          echo "Value 7: $value7"
          echo "Value 8: $value8"
          echo "Value 9: $value9"
          echo "Value 10: $value10"
          echo "Value 11: $value11"
          echo "Value 12: $value12"
          echo "Value 13: $value13"
          echo "Value 14: $value14"
          echo "Value 15: $value15"
          echo "Value 16: $value16"
          echo "Value 17: $value17"
          echo "Value 18: $value18"
          echo "Value 19: $value19"
          echo "Value 20: $value20"

