name: String Parser and Assignment for 20 Questions

on:
  workflow_dispatch:
    inputs:
      input_string:
        description: 'Enter 20 comma-separated values (Answers for 20 questions)'
        required: true
        default: 'ans1,ans2,ans3,ans4,ans5,ans6,ans7,ans8,ans9,ans10,ans11,ans12,ans13,ans14,ans15,ans16,ans17,ans18,ans19,ans20'

jobs:
  parse_and_assign:
    runs-on: ubuntu-latest
    steps:
     
      - name: Parse the input string and export as environment variables
        id: parse
        env:
          INPUT_STRING: ${{ github.event.inputs.input_string }}
        run: |
          echo "Parsing input string into 20 answers..."

          IFS=',' read -ra VALUES <<< "$INPUT_STRING"

          if [ "${#VALUES[@]}" -ne 20 ]; then
            echo "Error: Expected 20 answers, but got ${#VALUES[@]} values!"
            exit 1
          fi

          for i in "${!VALUES[@]}"; do
            index=$((i + 1))
            answer_var="answer$index"
            echo "$answer_var=${VALUES[i]}" >> $GITHUB_ENV
          done

      - name: Print each parsed answer with question mapping
        run: |
          echo "Mapping of Questions to Answers:"
          echo "Question 1 Answer: $answer1"
          echo "Question 2 Answer: $answer2"
          echo "Question 3 Answer: $answer3"
          echo "Question 4 Answer: $answer4"
          echo "Question 5 Answer: $answer5"
          echo "Question 6 Answer: $answer6"
          echo "Question 7 Answer: $answer7"
          echo "Question 8 Answer: $answer8"
          echo "Question 9 Answer: $answer9"
          echo "Question 10 Answer: $answer10"
          echo "Question 11 Answer: $answer11"
          echo "Question 12 Answer: $answer12"
          echo "Question 13 Answer: $answer13"
          echo "Question 14 Answer: $answer14"
          echo "Question 15 Answer: $answer15"
          echo "Question 16 Answer: $answer16"
          echo "Question 17 Answer: $answer17"
          echo "Question 18 Answer: $answer18"
          echo "Question 19 Answer: $answer19"
          echo "Question 20 Answer: $answer20"
